data:
  logfile_path: alerts.json
  report_path: reports/report.pdf
  video_path: video/video.mp4
  res_images_dir: detections/

model: 
  name: yolo11n.pt
  pretrained: True

inference:
  name: yolo11n.onnx
  conf: 0.3
  img_size: 320
  classes: ["person"]
  camera_index: 0
  device: cpu
  tracker: bytetrack.yaml
  stream: True 
