data:
  report_path: reports/report.pdf
  video_path: video/video.mp4

model_train: 
  name: yolo11n.pt
  path: src/models/yolo11n.pt

inference:
  export_format: ncnn
  path: src/models/yolo11n.ncnn
  tracker: bytetrack.yaml

  conf: 0.3
  classes: ["person"]

  img_size: 320
  camera_index: 0
  device: cpu
  stream: True 

  log_path: alerts.json
  res_img_dir: detections/